{
 "title": "Flask Backend Dashboard",
 "tags": [
  "flask",
  "backend"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Response Time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le)) \r\nOR on() vector(0)",
     "legendFormat": "p95 {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(flask_http_request_total{status=~\"5..\"}[1m])) \r\n  / \r\n  (sum(rate(flask_http_request_total[1m])) > 0) \r\n  * 100\r\n) \r\nOR on() vector(0)",
     "legendFormat": "5xx Errors"
    }
   ]
  },
  {
   "title": "Success Rate (2xx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_total{status=~\"2..\"}[1m])) / (sum(rate(flask_http_request_total[1m])) > 0) * 100) OR on() vector(100)",
     "legendFormat": "Successful Requests"
    }
   ]
  }
 ]
}