jenkins:
  systemMessage: "Jenkins - CloudRift CI/CD (JCasC)"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD:-admin123}"
        - id: "developer"
          password: "${DEV_PASSWORD:-dev123}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "developer"
            description: "Jenkins developers"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Cancel"
              - "Job/Read"
              - "Job/Workspace"
              - "View/Read"
            assignments:
              - "developer"

  remotingSecurity:
    enabled: true

  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_HOST"
            value: "unix:///var/run/docker.sock"

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"

  nodejs:
    installations:
      - name: "NodeJS-18"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "18.19.0"

  dockerTool:
    installations:
      - name: "Docker"
        properties:
          - installSource:
              installers:
                - fromDocker:
                    version: "latest"

unclassified:
  location:
    adminAddress: "admin@example.com"
    url: "${JENKINS_URL:-http://localhost:8080/}"

  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false

  globalLibraries:
    libraries:
      - name: "shared-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/AlexBoyev/CloudRift-devops.git"

  docker:
    dockerhosts:
      - uri: "unix:///var/run/docker.sock"

security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy

credentials:
  system:
    domainCredentials:
      - credentials:
          # Generic GitHub credential used by JCasC jobs (Job DSL)
          - usernamePassword:
              scope: GLOBAL
              id: "github-credentials"
              username: "${GITHUB_USERNAME:-admin}"
              password: "${GITHUB_TOKEN:-admin123}"
              description: "GitHub credentials for repository access"

          # These 3 match your pipelines (as you named them in Jenkinsfile.backend)
          # If you already created them in Jenkins UI, keep the IDs identical and remove these from JCasC.
          - usernamePassword:
              scope: GLOBAL
              id: "github-pat-token"
              username: "${GITHUB_PAT_USERNAME:-x-access-token}"
              password: "${GITHUB_PAT_TOKEN:-dummy-token}"
              description: "GitHub PAT token (Username/Password). Username often 'x-access-token'."

          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "ec2-ssh-key"
              username: "${EC2_SSH_USER:-ubuntu}"
              privateKeySource:
                directEntry:
                  privateKey: "${EC2_SSH_PRIVATE_KEY:-dummy-key}"
              description: "SSH private key for EC2 access"

          - string:
              scope: GLOBAL
              id: "ec2-host-ip"
              secret: "${EC2_HOST_IP_OR_DNS:-ec2-44-200-153-213.compute-1.amazonaws.com}"
              description: "EC2 host DNS or IP used by pipelines"

          - string:
              scope: GLOBAL
              id: "docker-hub-token"
              secret: "${DOCKER_HUB_TOKEN:-dummy-token}"
              description: "Docker Hub access token"

jobs:
  - script: >
      // ==========================================================
      // CloudRift pipelines:
      // - All Jenkinsfiles are stored in CloudRift-devops
      // - Each repo triggers only its own pipeline via remote token
      // ==========================================================

      folder('CloudRift') {
        displayName('CloudRift')
        description('CloudRift CI/CD jobs (triggered by GitHub webhooks)')
      }

      // FRONTEND PIPELINE (Triggered by CloudRift-frontend webhook)
      pipelineJob('CloudRift/frontend-pipeline') {
        displayName('Frontend CI/CD Pipeline')
        description('Frontend pipeline. Jenkinsfile stored in CloudRift-devops. Triggered via remote token.')
        authenticationToken('frontend-trigger')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AlexBoyev/CloudRift-devops.git')
                  credentials('github-credentials')
                }
                branches('*/main')
                scriptPath('devops-infra/jenkins/Jenkinsfile.frontend')
              }
            }
          }
        }
        // DO NOT add githubPush() here; SCM is devops and would trigger on devops pushes.
      }

      // BACKEND PIPELINE (Triggered by CloudRift-backend webhook)
      pipelineJob('CloudRift/backend-pipeline') {
        displayName('Backend CI/CD Pipeline')
        description('Backend pipeline. Jenkinsfile stored in CloudRift-devops. Triggered via remote token.')
        authenticationToken('backend-trigger')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AlexBoyev/CloudRift-devops.git')
                  credentials('github-credentials')
                }
                branches('*/main')
                scriptPath('devops-infra/jenkins/Jenkinsfile.backend')
              }
            }
          }
        }
      }

      // DEVOPS PIPELINE (Triggered by CloudRift-devops webhook)
      pipelineJob('CloudRift/devops-pipeline') {
        displayName('DevOps Pipeline')
        description('DevOps pipeline. Jenkinsfile stored in CloudRift-devops. Triggered via remote token.')
        authenticationToken('devops-trigger')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AlexBoyev/CloudRift-devops.git')
                  credentials('github-credentials')
                }
                branches('*/main')
                scriptPath('devops-infra/jenkins/Jenkinsfile.devops')
              }
            }
          }
        }
      }
