jenkins:
  systemMessage: "Jenkins - CloudRift CI/CD (JCasC)"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD:-admin123}"
        - id: "developer"
          password: "${DEV_PASSWORD:-dev123}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "developer"
            description: "Jenkins developers"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Cancel"
              - "Job/Read"
              - "Job/Workspace"
              - "View/Read"
            assignments:
              - "developer"

  remotingSecurity:
    enabled: true

  # CRITICAL: CSRF Protection - Allow GitHub webhooks
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true

  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_HOST"
            value: "unix:///var/run/docker.sock"

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"

  nodejs:
    installations:
      - name: "NodeJS-18"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "18.19.0"

  dockerTool:
    installations:
      - name: "Docker"
        properties:
          - installSource:
              installers:
                - fromDocker:
                    version: "latest"

unclassified:
  location:
    adminAddress: "admin@example.com"
    url: "${JENKINS_URL:-http://localhost:8080/}"

  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false

  globalLibraries:
    libraries:
      - name: "shared-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/AlexBoyev/CloudRift-devops.git"

  docker:
    dockerhosts:
      - uri: "unix:///var/run/docker.sock"

  # GitHub configuration for webhook integration
  githubpluginconfig:
    configs:
      - name: "GitHub"
        apiUrl: "https://api.github.com"
        manageHooks: true
        credentialsId: "github-pat-token"

security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy

  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-credentials"
              username: "${GITHUB_USERNAME:-admin}"
              password: "${GITHUB_TOKEN:-admin123}"
              description: "GitHub credentials for repository access"

          - usernamePassword:
              scope: GLOBAL
              id: "github-pat-token"
              username: "${GITHUB_PAT_USERNAME:-x-access-token}"
              password: "${GITHUB_PAT_TOKEN:-dummy-token}"
              description: "GitHub PAT token (Username/Password). Username often 'x-access-token'."

          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "ec2-ssh-key"
              username: "${EC2_SSH_USER:-ubuntu}"
              privateKeySource:
                directEntry:
                  privateKey: "${EC2_SSH_PRIVATE_KEY:-dummy-key}"
              description: "SSH private key for EC2 access"

          - string:
              scope: GLOBAL
              id: "ec2-host-ip"
              secret: "${EC2_HOST_IP_OR_DNS:-ec2-44-200-153-213.compute-1.amazonaws.com}"
              description: "EC2 host DNS or IP used by pipelines"

          - string:
              scope: GLOBAL
              id: "docker-hub-token"
              secret: "${DOCKER_HUB_TOKEN:-dummy-token}"
              description: "Docker Hub access token"

          # GitHub webhook secret for security
          - string:
              scope: GLOBAL
              id: "github-webhook-secret"
              secret: "${GITHUB_WEBHOOK_SECRET:-change-me-to-random-string}"
              description: "Secret for GitHub webhook validation"

jobs:
  - script: >
      folder('CloudRift') {
        displayName('CloudRift')
        description('CloudRift CI/CD jobs (triggered by GitHub webhooks)')
      }

      pipelineJob('CloudRift/frontend-pipeline') {
        displayName('Frontend CI/CD Pipeline')
        description('Frontend pipeline triggered by GitHub webhook on push to CloudRift-frontend')
        
        properties {
          githubProjectUrl('https://github.com/AlexBoyev/CloudRift-frontend')
          pipelineTriggers {
            triggers {
              githubPush()
            }
          }
        }
        
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AlexBoyev/CloudRift-devops.git')
                  credentials('github-pat-token')
                }
                branches('*/main')
                scriptPath('devops-infra/jenkins/Jenkinsfile.frontend')
              }
            }
          }
        }
      }

      pipelineJob('CloudRift/backend-pipeline') {
        displayName('Backend CI/CD Pipeline')
        description('Backend pipeline triggered by GitHub webhook on push to CloudRift-backend')
        
        properties {
          githubProjectUrl('https://github.com/AlexBoyev/CloudRift-backend')
          pipelineTriggers {
            triggers {
              githubPush()
            }
          }
        }
        
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AlexBoyev/CloudRift-devops.git')
                  credentials('github-pat-token')
                }
                branches('*/main')
                scriptPath('devops-infra/jenkins/Jenkinsfile.backend')
              }
            }
          }
        }
      }

      pipelineJob('CloudRift/devops-pipeline') {
        displayName('DevOps Pipeline')
        description('DevOps pipeline triggered by GitHub webhook on push to CloudRift-devops')
        
        properties {
          githubProjectUrl('https://github.com/AlexBoyev/CloudRift-devops')
          pipelineTriggers {
            triggers {
              githubPush()
            }
          }
        }
        
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AlexBoyev/CloudRift-devops.git')
                  credentials('github-pat-token')
                }
                branches('*/main')
                scriptPath('devops-infra/jenkins/Jenkinsfile')
              }
            }
          }
        }
      }